<template>
    <div class="modal-type" v-show="visible">
        <div class="item" v-for="item in list" :key="item.name" @click="itemClick(item)">
            {{item.name}}
        </div>
    </div>
</template>
<script>
export default {
  name: "modalType",
  props:{
      visible:{
         type:Boolean,
         default:false 
      }
  },
  data () {
    return {
        list:[
            {
                name:'绝句',
                children:[
                    {
                       key:1,
                       label:'五言绝句' 
                    },
                    {
                        key:2,
                        label:'七言绝句'
                    }
                ]
            },
            {
                name:'风格绝句',
                children:[
                    {
                       key:1,
                       label:'五言绝句' 
                    },
                    {
                        key:2,
                        label:'七言绝句'
                    }
                ] 
            },
            {
                name:'藏头诗',
                children:[
                    {
                        key:1,
                        label:'五言藏头'
                    },
                    {
                        key:2,
                        label:'七言藏头'
                    }
                ]
            },
            {
                name:'律诗',
                children:[
                    {
                        key:1,
                        label:'五言律诗'
                    },
                    {
                        key:2,
                        label:'七言律诗'
                    }
                ] 
            },
            {
                name:'集句诗',
                children:[
                    {
                        key:1,
                        label:'集句诗'
                    }
                ]
            }
        ]
    };
  },
  methods:{
      itemClick(item){
          this.$emit('currentModalItem',item);
          // this.$emit('closeModal',false);
      }
  }
}
</script>
<style lang="scss" scoped>
    .modal-type{
        width:100%;
        height:100%;
        position:fixed;
        top:0;
        left:0;
        background:rgba(255,255,255,.6);
        z-index:999;
        display:flex;
        justify-content:center;
        align-items:center;
        .item{
            width:180px;
            height:180px;
            border-radius:50%;
            background:#d5c27e;
            display:flex;
            justify-content:center;
            align-items:center;
            font-size:27px;
            color:#fff;
            margin-right:80px;
            cursor: pointer;
            &:last-child{
                margin-right:0;
            }
        }
    }
</style>